// Build the browser-only version for GitHub Pages:  npm run build:pages   ->  dist/
//   dist/engine.worker.js   the whole game (rules + bots + SQLite glue) bundled for the browser
//   dist/sqlite3.wasm       SQLite compiled to WebAssembly (found next to the worker via import.meta.url)
//   dist/index.html ...     the frontend (public/) with config.js switched to local mode
//   dist/assets.json        which art files exist (there is no server to ask)
import { copyFileSync, cpSync, mkdirSync, rmSync, statSync, writeFileSync } from 'node:fs';
import { build } from 'esbuild';
import { listAssets } from '../src/assets.ts';

// Two builds:
//   npm run build:pages                                   browser-only single-player game (engine + SQLite in a Web Worker)  -> dist/
//   npm run build:online -- --api https://game.example.com   just the frontend, talking to YOUR game server (for itch.io etc.)  -> dist-online/
const args = process.argv.slice(2);
const apiIdx = args.indexOf('--api');
const api = apiIdx >= 0 ? (args[apiIdx + 1] ?? '') : null;
const okAddress = (u: string) => /^https:\/\/[^\s/]+(:\d+)?$/.test(u) || /^http:\/\/(localhost|127\.0\.0\.1)(:\d+)?$/.test(u); // http only for local testing
if (api !== null && !okAddress(api.replace(/\/+$/, ''))) {
  console.error('Usage: npm run build:online -- --api https://your-game-server.example.com   (https is required: itch.io and GitHub Pages are https sites; plain http only for localhost)');
  process.exit(1);
}
const out = args.find((a, i) => !a.startsWith('--') && args[i - 1] !== '--api') ?? (api !== null ? 'dist-online' : 'dist');
rmSync(out, { recursive: true, force: true });
mkdirSync(out, { recursive: true });

if (api === null) {
  await build({
    entryPoints: ['src/browser/engine.worker.ts'],
    bundle: true, format: 'esm', platform: 'browser', target: 'es2022',
    outfile: `${out}/engine.worker.js`, minify: true, legalComments: 'none', logLevel: 'warning',
    alias: { 'node:crypto': './src/browser/crypto-shim.ts' }, // password hashing without Node
  });
  copyFileSync('node_modules/@sqlite.org/sqlite-wasm/dist/sqlite3.wasm', `${out}/sqlite3.wasm`);
  copyFileSync('node_modules/@sqlite.org/sqlite-wasm/dist/sqlite3-opfs-async-proxy.js', `${out}/sqlite3-opfs-async-proxy.js`); // referenced by the library, unused by us
}

cpSync('public', out, { recursive: true });
writeFileSync(`${out}/config.js`, api === null
  ? '// generated by scripts/build-pages.ts (browser-only build)\nwindow.MG_LOCAL = true;\nwindow.MG_API = \'\';\n'
  : `// generated by scripts/build-pages.ts (online build): the game runs on your server, this page is only the frontend\nwindow.MG_LOCAL = false;\nwindow.MG_API = ${JSON.stringify(api.replace(/\/+$/, ''))};\n`);
writeFileSync(`${out}/assets.json`, JSON.stringify(listAssets(out)));
writeFileSync(`${out}/.nojekyll`, ''); // GitHub Pages: serve files as they are

console.log(`built ${out}/ (${api === null ? `browser-only, engine ${(statSync(`${out}/engine.worker.js`).size / 1024).toFixed(0)} KB` : `frontend for the server ${api}`}, ${Object.keys(listAssets(out)).length} art files)`);
